version: "3.1"

services:
  db:
    container_name: AyZiWai-DB
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_DATABASE: "AyZiWai"
    volumes:
      - db:/data/db
    networks:
      - network-data

  spring-app:
    container_name: AyZiWai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@db:27017/AyZiWai?authSource=admin
    networks:
      - network-data
    depends_on:
      - db

  # jenkins:
  #   container_name: AyZiWai-Jenkins
  #   image: "jenkins/jenkins:lts"
  #   restart: always
  #   user: root
  #   ports:
  #     - "9090:8080"
  #     - "50000:50000"
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - network-data
  #   environment:
  #     - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

networks:
  network-data:
    driver: bridge

volumes:
  db:
    driver: local
  # jenkins_home:
  #   driver: local
